//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Ателье
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T статус заказа.
    /// </summary>
    // *** Start programmer edit section *** (tСтатусЗаказа CustomAttributes)

    // *** End programmer edit section *** (tСтатусЗаказа CustomAttributes)
    public enum tСтатусЗаказа
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tСтатусЗаказа.ВРаботе CustomAttributes)

        // *** End programmer edit section *** (tСтатусЗаказа.ВРаботе CustomAttributes)
        ВРаботе,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tСтатусЗаказа.ОжидаетКлиента CustomAttributes)

        // *** End programmer edit section *** (tСтатусЗаказа.ОжидаетКлиента CustomAttributes)
        ОжидаетКлиента,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tСтатусЗаказа.Завершён CustomAttributes)

        // *** End programmer edit section *** (tСтатусЗаказа.Завершён CustomAttributes)
        Завершён,
    }
}
