//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Ателье
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "КодКлиента as \'Код клиента\'",
            "ФИОКлиента as \'Ф и о клиента\'",
            "ТелефонКлиента as \'Телефон клиента\'",
            "Мастер"})]
    [MasterViewDefineAttribute("КлиентE", "Мастер", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОМастера")]
    [View("КлиентL", new string[] {
            "КодКлиента as \'Код клиента\'",
            "ФИОКлиента as \'Ф и о клиента\'",
            "ТелефонКлиента as \'Телефон клиента\'",
            "Мастер.ФИОМастера as \'ФИО Мастера\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодКлиента;
        
        private string fФИОКлиента;
        
        private string fТелефонКлиента;
        
        private IIS.АСУ_Ателье.Мастер fМастер;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// КодКлиента.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.КодКлиента CustomAttributes)

        // *** End programmer edit section *** (Клиент.КодКлиента CustomAttributes)
        [DisableInsertProperty(true)]
        [NotNull()]
        public virtual int КодКлиента
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.КодКлиента Get start)

                // *** End programmer edit section *** (Клиент.КодКлиента Get start)
                int result = this.fКодКлиента;
                // *** Start programmer edit section *** (Клиент.КодКлиента Get end)

                // *** End programmer edit section *** (Клиент.КодКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.КодКлиента Set start)

                // *** End programmer edit section *** (Клиент.КодКлиента Set start)
                this.fКодКлиента = value;
                // *** Start programmer edit section *** (Клиент.КодКлиента Set end)

                // *** End programmer edit section *** (Клиент.КодКлиента Set end)
            }
        }
        
        /// <summary>
        /// ФИОКлиента.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ФИОКлиента CustomAttributes)

        // *** End programmer edit section *** (Клиент.ФИОКлиента CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ФИОКлиента
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ФИОКлиента Get start)

                // *** End programmer edit section *** (Клиент.ФИОКлиента Get start)
                string result = this.fФИОКлиента;
                // *** Start programmer edit section *** (Клиент.ФИОКлиента Get end)

                // *** End programmer edit section *** (Клиент.ФИОКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ФИОКлиента Set start)

                // *** End programmer edit section *** (Клиент.ФИОКлиента Set start)
                this.fФИОКлиента = value;
                // *** Start programmer edit section *** (Клиент.ФИОКлиента Set end)

                // *** End programmer edit section *** (Клиент.ФИОКлиента Set end)
            }
        }
        
        /// <summary>
        /// ТелефонКлиента.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ТелефонКлиента CustomAttributes)

        // *** End programmer edit section *** (Клиент.ТелефонКлиента CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ТелефонКлиента
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ТелефонКлиента Get start)

                // *** End programmer edit section *** (Клиент.ТелефонКлиента Get start)
                string result = this.fТелефонКлиента;
                // *** Start programmer edit section *** (Клиент.ТелефонКлиента Get end)

                // *** End programmer edit section *** (Клиент.ТелефонКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ТелефонКлиента Set start)

                // *** End programmer edit section *** (Клиент.ТелефонКлиента Set start)
                this.fТелефонКлиента = value;
                // *** Start programmer edit section *** (Клиент.ТелефонКлиента Set end)

                // *** End programmer edit section *** (Клиент.ТелефонКлиента Set end)
            }
        }
        
        /// <summary>
        /// Клиент.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Мастер CustomAttributes)

        // *** End programmer edit section *** (Клиент.Мастер CustomAttributes)
        [PropertyStorage(new string[] {
                "Мастер"})]
        public virtual IIS.АСУ_Ателье.Мастер Мастер
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Мастер Get start)

                // *** End programmer edit section *** (Клиент.Мастер Get start)
                IIS.АСУ_Ателье.Мастер result = this.fМастер;
                // *** Start programmer edit section *** (Клиент.Мастер Get end)

                // *** End programmer edit section *** (Клиент.Мастер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Мастер Set start)

                // *** End programmer edit section *** (Клиент.Мастер Set start)
                this.fМастер = value;
                // *** Start programmer edit section *** (Клиент.Мастер Set end)

                // *** End programmer edit section *** (Клиент.Мастер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.АСУ_Ателье.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.АСУ_Ателье.Клиент));
                }
            }
        }
    }
}
