//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Ателье
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Мастер.
    /// </summary>
    // *** Start programmer edit section *** (Мастер CustomAttributes)

    // *** End programmer edit section *** (Мастер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МастерE", new string[] {
            "КодМастера as \'Код мастера\'",
            "ФИОМастера as \'Ф и о мастера\'",
            "Цех"})]
    [MasterViewDefineAttribute("МастерE", "Цех", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаименованиеЦеха")]
    [View("МастерL", new string[] {
            "КодМастера as \'Код мастера\'",
            "ФИОМастера as \'ФИО мастера\'",
            "Цех.НаименованиеЦеха as \'Цех\'"})]
    public class Мастер : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодМастера;
        
        private string fФИОМастера;
        
        private IIS.АСУ_Ателье.Цех fЦех;
        
        // *** Start programmer edit section *** (Мастер CustomMembers)

        // *** End programmer edit section *** (Мастер CustomMembers)

        
        /// <summary>
        /// КодМастера.
        /// </summary>
        // *** Start programmer edit section *** (Мастер.КодМастера CustomAttributes)

        // *** End programmer edit section *** (Мастер.КодМастера CustomAttributes)
        [DisableInsertProperty(true)]
        [NotNull()]
        public virtual int КодМастера
        {
            get
            {
                // *** Start programmer edit section *** (Мастер.КодМастера Get start)

                // *** End programmer edit section *** (Мастер.КодМастера Get start)
                int result = this.fКодМастера;
                // *** Start programmer edit section *** (Мастер.КодМастера Get end)

                // *** End programmer edit section *** (Мастер.КодМастера Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Мастер.КодМастера Set start)

                // *** End programmer edit section *** (Мастер.КодМастера Set start)
                this.fКодМастера = value;
                // *** Start programmer edit section *** (Мастер.КодМастера Set end)

                // *** End programmer edit section *** (Мастер.КодМастера Set end)
            }
        }
        
        /// <summary>
        /// ФИОМастера.
        /// </summary>
        // *** Start programmer edit section *** (Мастер.ФИОМастера CustomAttributes)

        // *** End programmer edit section *** (Мастер.ФИОМастера CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ФИОМастера
        {
            get
            {
                // *** Start programmer edit section *** (Мастер.ФИОМастера Get start)

                // *** End programmer edit section *** (Мастер.ФИОМастера Get start)
                string result = this.fФИОМастера;
                // *** Start programmer edit section *** (Мастер.ФИОМастера Get end)

                // *** End programmer edit section *** (Мастер.ФИОМастера Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Мастер.ФИОМастера Set start)

                // *** End programmer edit section *** (Мастер.ФИОМастера Set start)
                this.fФИОМастера = value;
                // *** Start programmer edit section *** (Мастер.ФИОМастера Set end)

                // *** End programmer edit section *** (Мастер.ФИОМастера Set end)
            }
        }
        
        /// <summary>
        /// Мастер.
        /// </summary>
        // *** Start programmer edit section *** (Мастер.Цех CustomAttributes)

        // *** End programmer edit section *** (Мастер.Цех CustomAttributes)
        [PropertyStorage(new string[] {
                "Цех"})]
        public virtual IIS.АСУ_Ателье.Цех Цех
        {
            get
            {
                // *** Start programmer edit section *** (Мастер.Цех Get start)

                // *** End programmer edit section *** (Мастер.Цех Get start)
                IIS.АСУ_Ателье.Цех result = this.fЦех;
                // *** Start programmer edit section *** (Мастер.Цех Get end)

                // *** End programmer edit section *** (Мастер.Цех Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Мастер.Цех Set start)

                // *** End programmer edit section *** (Мастер.Цех Set start)
                this.fЦех = value;
                // *** Start programmer edit section *** (Мастер.Цех Set end)

                // *** End programmer edit section *** (Мастер.Цех Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МастерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МастерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МастерE", typeof(IIS.АСУ_Ателье.Мастер));
                }
            }
            
            /// <summary>
            /// "МастерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МастерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МастерL", typeof(IIS.АСУ_Ателье.Мастер));
                }
            }
        }
    }
}
