//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Ателье
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Модель одежды.
    /// </summary>
    // *** Start programmer edit section *** (МодельОдежды CustomAttributes)

    // *** End programmer edit section *** (МодельОдежды CustomAttributes)
    [AutoAltered()]
    [Caption("Модель одежды")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МодельОдеждыE", new string[] {
            "КодМодели",
            "НазваниеМодели",
            "РазмерМодели"})]
    [View("МодельОдеждыL", new string[] {
            "КодМодели",
            "НазваниеМодели",
            "РазмерМодели"})]
    public class МодельОдежды : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодМодели;
        
        private string fНазваниеМодели;
        
        private int fРазмерМодели;
        
        // *** Start programmer edit section *** (МодельОдежды CustomMembers)

        // *** End programmer edit section *** (МодельОдежды CustomMembers)

        
        /// <summary>
        /// КодМодели.
        /// </summary>
        // *** Start programmer edit section *** (МодельОдежды.КодМодели CustomAttributes)

        // *** End programmer edit section *** (МодельОдежды.КодМодели CustomAttributes)
        [DisableInsertProperty(true)]
        [NotNull()]
        public virtual int КодМодели
        {
            get
            {
                // *** Start programmer edit section *** (МодельОдежды.КодМодели Get start)

                // *** End programmer edit section *** (МодельОдежды.КодМодели Get start)
                int result = this.fКодМодели;
                // *** Start programmer edit section *** (МодельОдежды.КодМодели Get end)

                // *** End programmer edit section *** (МодельОдежды.КодМодели Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (МодельОдежды.КодМодели Set start)

                // *** End programmer edit section *** (МодельОдежды.КодМодели Set start)
                this.fКодМодели = value;
                // *** Start programmer edit section *** (МодельОдежды.КодМодели Set end)

                // *** End programmer edit section *** (МодельОдежды.КодМодели Set end)
            }
        }
        
        /// <summary>
        /// НазваниеМодели.
        /// </summary>
        // *** Start programmer edit section *** (МодельОдежды.НазваниеМодели CustomAttributes)

        // *** End programmer edit section *** (МодельОдежды.НазваниеМодели CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string НазваниеМодели
        {
            get
            {
                // *** Start programmer edit section *** (МодельОдежды.НазваниеМодели Get start)

                // *** End programmer edit section *** (МодельОдежды.НазваниеМодели Get start)
                string result = this.fНазваниеМодели;
                // *** Start programmer edit section *** (МодельОдежды.НазваниеМодели Get end)

                // *** End programmer edit section *** (МодельОдежды.НазваниеМодели Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (МодельОдежды.НазваниеМодели Set start)

                // *** End programmer edit section *** (МодельОдежды.НазваниеМодели Set start)
                this.fНазваниеМодели = value;
                // *** Start programmer edit section *** (МодельОдежды.НазваниеМодели Set end)

                // *** End programmer edit section *** (МодельОдежды.НазваниеМодели Set end)
            }
        }
        
        /// <summary>
        /// РазмерМодели.
        /// </summary>
        // *** Start programmer edit section *** (МодельОдежды.РазмерМодели CustomAttributes)

        // *** End programmer edit section *** (МодельОдежды.РазмерМодели CustomAttributes)
        [NotNull()]
        public virtual int РазмерМодели
        {
            get
            {
                // *** Start programmer edit section *** (МодельОдежды.РазмерМодели Get start)

                // *** End programmer edit section *** (МодельОдежды.РазмерМодели Get start)
                int result = this.fРазмерМодели;
                // *** Start programmer edit section *** (МодельОдежды.РазмерМодели Get end)

                // *** End programmer edit section *** (МодельОдежды.РазмерМодели Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (МодельОдежды.РазмерМодели Set start)

                // *** End programmer edit section *** (МодельОдежды.РазмерМодели Set start)
                this.fРазмерМодели = value;
                // *** Start programmer edit section *** (МодельОдежды.РазмерМодели Set end)

                // *** End programmer edit section *** (МодельОдежды.РазмерМодели Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МодельОдеждыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МодельОдеждыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МодельОдеждыE", typeof(IIS.АСУ_Ателье.МодельОдежды));
                }
            }
            
            /// <summary>
            /// "МодельОдеждыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МодельОдеждыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МодельОдеждыL", typeof(IIS.АСУ_Ателье.МодельОдежды));
                }
            }
        }
    }
}
