//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Ателье
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сервер БЛ.
    /// </summary>
    // *** Start programmer edit section *** (BFСерверБЛ CustomAttributes)

    // *** End programmer edit section *** (BFСерверБЛ CustomAttributes)
    public class BFСерверБЛ : ICSSoft.STORMNET.Business.BFBase
    {
        
        // *** Start programmer edit section *** (BFСерверБЛ CustomMembers)

        // *** End programmer edit section *** (BFСерверБЛ CustomMembers)

    }
}
