//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Ателье
{
    using ICSSoft.STORMNET;
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сервер БЛ.
    /// </summary>
    // *** Start programmer edit section *** (СерверБЛ CustomAttributes)

    // *** End programmer edit section *** (СерверБЛ CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class СерверБЛ : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (СерверБЛ CustomMembers)

        // *** End programmer edit section *** (СерверБЛ CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateЗаказ CustomAttributes)

        // *** End programmer edit section *** (OnUpdateЗаказ CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateЗаказ(IIS.АСУ_Ателье.Заказ UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateЗаказ)
            if (UpdatedObject.GetStatus() == ObjectStatus.Created)
            {
                UpdatedObject.ДатаПоступления = DateTime.Now;
            }

            if (UpdatedObject.GetStatus() == ObjectStatus.Altered && UpdatedObject.СтатусЗаказа == tСтатусЗаказа.Завершён)
            {
                UpdatedObject.LockObject(UpdatedObject.СтатусЗаказа);
                UpdatedObject.ДатаЗакрытия = DateTime.Now;
            }

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateЗаказ)
        }
    }
}
